Capture memory also as part of monitor samples
ludeknovy/jtl-reporter-listener-service pull request #49
Opened 2024-06-11 12:04 UTC by puran157

Capture Memory while logging samples.

Planning to edit https://github.com/ludeknovy/jtl-reporter/blob/main/scripts/jtl_listener_service.py and other files as well.
LMK if change looks good and then I can work on scripts.

2024-06-11 12:38 UTC, ludeknovy commented
Hi @puran157 . Thanks for your contribution. I think in such a case it would be better to either create new API version, as the current change would break it for the older version ( you defined `mem` as required field) or the `mem` must be made optional.

2024-06-12 04:59 UTC, puran157 commented
> Hi @puran157 . Thanks for your contribution. I think in such a case it would be better to either create new API version, as the current change would break it for the older version ( you defined `mem` as required field) or the `mem` must be made optional.

Cool, let me make  it optional

2024-06-13 08:02 UTC, puran157 commented
> Hi @puran157 . Thanks for your contribution. I think in such a case it would be better to either create new API version, as the current change would break it for the older version ( you defined `mem` as required field) or the `mem` must be made optional.

Done, made mem optional

2024-06-14 07:49 UTC, ludeknovy requested changes

2024-06-14 07:49 UTC, ludeknovy commented on src/db/columnSets.ts
> +  "timestamp", "name", "cpu", "mem", {
This is a breaking change, if "mem" wont be provided, the API will throw 500

2024-06-14 08:08 UTC, ludeknovy commented on src/db/columnSets.ts
> +  "timestamp", "name", "cpu", "mem", {
I've created new MR with v4: https://github.com/ludeknovy/jtl-reporter-listener-service/pull/50

2024-06-14 08:16 UTC, ludeknovy commented
Closing it, as https://github.com/ludeknovy/jtl-reporter-listener-service/pull/50 was merged. 
You can test it using the `latest` tag once this job is finished: https://github.com/ludeknovy/jtl-reporter-listener-service/actions/runs/9512898377

2024-06-14 08:16 UTC, closed without merging